"use client";

import Sidebar from "../components/Sidebar";
import AssistantChat from "../components/AssistantChat";
import { FileText, Calendar as CalendarIcon, Clock } from "lucide-react";

export default function AppointmentsPage() {
    return (
        <div className="min-h-screen bg-black text-white flex">
            <Sidebar />
            <main className="flex-1 md:ml-64 p-8">
                <header className="mb-12">
                    <h1 className="text-4xl font-bold mb-2">Appointments & Prep</h1>
                    <p className="text-neutral-400">Everything you need for your upcoming autonomous syncs.</p>
                </header>

                <div className="grid grid-cols-1 xl:grid-cols-3 gap-8">
                    <div className="xl:col-span-2 space-y-8">
                        <section>
                            <h3 className="text-xl font-semibold mb-6">Upcoming Schedule</h3>
                            <div className="space-y-4">
                                {[
                                    { time: "Tomorrow, 10:00 AM", title: "Strategic Vision Sync", type: "Internal", attendee: "Ops Team" },
                                    { time: "Friday, 2:30 PM", title: "Enterprise Partnership Review", type: "Client", attendee: "Fortune 500 Lead" },
                                ].map((appt, i) => (
                                    <div key={i} className="flex items-center gap-6 p-6 rounded-3xl bg-neutral-900 border border-neutral-800">
                                        <div className="p-4 rounded-2xl bg-purple-500/10 text-purple-400">
                                            <CalendarIcon size={24} />
                                        </div>
                                        <div className="flex-1">
                                            <div className="text-sm text-neutral-500 mb-1 flex items-center gap-2">
                                                <Clock size={12} /> {appt.time}
                                            </div>
                                            <div className="text-lg font-bold">{appt.title}</div>
                                            <div className="text-sm text-neutral-400">With {appt.attendee}</div>
                                        </div>
                                        <button className="px-6 py-2 bg-neutral-800 rounded-full text-xs font-bold hover:bg-neutral-700 transition-colors">Prepare</button>
                                    </div>
                                ))}
                            </div>
                        </section>
                    </div>

                    <div className="space-y-8">
                        <section>
                            <h3 className="text-xl font-semibold mb-6">Prep Materials</h3>
                            <div className="p-8 rounded-3xl bg-neutral-900 border border-neutral-800">
                                <p className="text-sm text-neutral-400 mb-6">Generated by Assistant for 'Strategic Vision Sync'</p>
                                <div className="space-y-4">
                                    {[
                                        "Q1 Performance Overview.pdf",
                                        "Competitor Analysis Beta.docx",
                                        "Financial Forecast v2.xlsx"
                                    ].map((file, i) => (
                                        <div key={i} className="flex items-center gap-3 p-3 rounded-xl bg-neutral-800/50 hover:bg-neutral-800 transition-colors cursor-pointer">
                                            <FileText size={18} className="text-neutral-500" />
                                            <span className="text-sm truncate">{file}</span>
                                        </div>
                                    ))}
                                </div>
                                <button className="w-full mt-8 py-3 bg-white text-black font-bold rounded-2xl hover:bg-neutral-200 transition-colors">View All Materials</button>
                            </div>
                        </section>
                    </div>
                </div>
            </main>
            <AssistantChat />
        </div>
    );
}
